### ISSUE TITLE
Zabbix v3.4.12 - No sending data for detecting CPU anomaly

### ISSUE THREAD

**Issue by Sebbo94BY** [ike-dai/zabbix_anomaly#3]
Operating System: Ubuntu 16.04.5 LTS (incl. all latest updates until today)
Zabbix Server, Agent and Frontend: v3.4.14

I would like to detect and show notifications about unusual CPU anomalies on the Zabbix dashboard.

Therefore, I've created these items in the "Template OS Linux":
**1) Name: CPU Anomaly Check**
Type: External check
Key: `zabbix_anomaly["-url","https://zabbix.example.com/api_jsonrpc.php","-i","10010","-user","anomaly.api","-pass","s3crEtP4ssw0rD","-interval","60"]`
Type of information: Character
Update interval: 60s
Applications: CPU

**2) Name: CPU Anomaly Score**
Type: Zabbix trapper
Key: `anomaly.system.cpu.load[percpu,avg1]`
Type of information: Numeric (float)
Applications: CPU

The item ID of the "_Processor load (1 min average per core)_" is `10010` from the "_Template OS Linux_". Due to this, I've set this ID at the item 1) above.

My problem is, that I'm only getting the message `[INFO]: No sending data`. I've already check issue #2 , but as you can see above, my values are already set to 60s - also in the mentioned CPU load item `10011`.

As soon as I'm getting correct values, I could add the required trigger, but right now, I don't get any values.

How can I solve this issue?

Note: I would like to have this anomaly check for all hosts - not only one. The URL and credentials are correct.

**Comment by Sebbo94BY** [comment]
Any idea? Anyone?

**Comment by ike-dai** [comment]
Sorry for late reply..
I have fixed this bug (for over Zabbix 3.4.0).

Please check this release version.
Only you should replace zabbix_anomaly binary file. (and set parmission)

https://github.com/ike-dai/zabbix_anomaly/releases/tag/0.0.8

**Comment by Sebbo94BY** [comment]
Thanks for the update, but it's still not working. :(

```
root@linux:/usr/lib/zabbix/externalscripts# stat zabbix_anomaly
  File: 'zabbix_anomaly'
  Size: 6095028         Blocks: 11912      IO Block: 4096   regular file
Device: fd01h/64769d    Inode: 525239      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-11-05 10:38:59.703991868 +0100
Modify: 2018-11-01 22:37:28.000000000 +0100
Change: 2018-11-05 10:38:58.684046548 +0100
 Birth: -
```

```
root@linux:/usr/lib/zabbix/externalscripts# ./zabbix_anomaly -url "https://zabbix.example.com/api_jsonrpc.php" -user 'anomaly.api' -pass 's3crEtP4ssw0rD' -i 10010 -interval 60; echo
[INFO]: No sending data
```

Item 10010 (_Processor load (1 min average per core)_) has the type of information "Numeric (float)".

**Comment by ike-dai** [comment]
Thank you for your reply.
I think item 10010 is "Template" Item.
So, item id 10010 doesn't have any monitoring data.
Please check "Host" item id.
[Configuration]->[Hosts]-><Your monitoring host Items link>->[Template OS Linux: Processor load (1 min average per core)]

My environment screen shot
![zabbix_anomaly_check](https://user-images.githubusercontent.com/137471/48207553-35bd0a80-e3b4-11e8-828a-06717d112f2d.png)

**Comment by Sebbo94BY** [comment]
Yes, it was the ID of the template as I want and need an anomaly check on all hosts and not only on the Zabbix server.

I've tried to the item ID from the Zabbix servers specific item: 23296.

But even with this it returned "No sending data".

**Comment by ike-dai** [comment]
> Yes, it was the ID of the template as I want and need an anomaly check on all hosts and not only on the Zabbix server.

Sorry, you must set each host item id in now specification...
I will consider that getting monitoring history data based on item name.

I fixed to convert suffix 's' at monitoring interval setting.
Please try again with v0.0.9. 
https://github.com/ike-dai/zabbix_anomaly/releases/tag/0.0.9

If you get same error, please show your item latest history data (item ID 23296).

**Comment by Sebbo94BY** [comment]
I've used the new version 0.0.9:
```
# ./zabbix_anomaly -url "https://zabbix.example.com/api_jsonrpc.php" -user 'anomaly.api' -pass 's3crEtP4ssw0rD' -i 23296 -interval 60
[INFO]: No sending data
```
![Screenshot of latest data for item ID 23296](https://i.imgur.com/BenTgqS.png)

**Comment by ike-dai** [comment]
Thanks.
Please try 2 points.

1. please set large value at "-interval" and "-n" optios. (e.g. -interval 36000 -n 100)
2. Please check permission of anomaly.api user.

**Comment by Sebbo94BY** [comment]
I've used your parameters and values - same result.

The anomaly.api user has full admin permissions while testing. At the end - when it's working - I'll restrict the permissions.

**Comment by ike-dai** [comment]
I have not reproduced you situation yet..
I implemented some debug messages to this zabbix_anomaly binary
Please check your output by using this binary.

[debug_bin.zip](https://github.com/ike-dai/zabbix_anomaly/files/2572315/debug_bin.zip)

```
$ zabbix_anomaly-linux-amd64_debug -h localhost -p 10051 -url http://localhost/zabbix/api_jsonrpc.php -i 23296 -user Admin -pass zabbix -interval 60

[DEBUG] from_time: 1542027462
[DEBUG] delay: 60
[DEBUG] history.get response: {2.0 <nil> [map[itemid:23296 clock:1542030640 value:0.2150 ns:482444385] map[itemid:23296 clock:1542030676 value:0.1600 ns:414666737] map[itemid:23296 clock:1542030736 value:0.0550 ns:860127521] map[itemid:23296 clock:1542030796 value:0.0600 ns:302243800] map[itemid:23296 clock:1542030856 value:0.0200 ns:901410064] map[itemid:23296 clock:1542032263 value:0.0150 ns:691726274] map[itemid:23296 clock:1542032296 value:0.0050 ns:34075646] map[ns:152895586 itemid:23296 clock:1542032757 value:0.4450] map[clock:1542032776 value:1.6500 ns:464986649 itemid:23296] map[itemid:23296 clock:1542032836 value:0.7700 ns:832458273] map[itemid:23296 clock:1542032896 value:0.3800 ns:301644610] map[itemid:23296 clock:1542032956 value:0.2200 ns:829365705] map[itemid:23296 clock:1542033016 value:0.1000 ns:163982830] map[value:0.0350 ns:638663498 itemid:23296 clock:1542033076] map[itemid:23296 clock:1542033136 value:0.0100 ns:866063805] map[itemid:23296 clock:1542033196 value:0.0550 ns:579381442] map[itemid:23296 clock:1542033256 value:0.0200 ns:199260731] map[itemid:23296 clock:1542033316 value:0.0450 ns:529418346] map[ns:474308763 itemid:23296 clock:1542033376 value:0.0150] map[itemid:23296 clock:1542033436 value:0.0050 ns:434583042]] 3}
[DEBUG] history: map[ns:482444385 itemid:23296 clock:1542030640 value:0.2150]
[DEBUG] history['clock']: 1542030640
[DEBUG] history clock: 1542030640, check clock: 1542033403
1542030640	0.2150	27.052036
[DEBUG] history: map[itemid:23296 clock:1542030676 value:0.1600 ns:414666737]
[DEBUG] history['clock']: 1542030676
[DEBUG] history clock: 1542030676, check clock: 1542033403
1542030676	0.1600	7.766502
[DEBUG] history: map[ns:860127521 itemid:23296 clock:1542030736 value:0.0550]
[DEBUG] history['clock']: 1542030736
[DEBUG] history clock: 1542030736, check clock: 1542033403
...
...
```
